# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = ["derive"]

[package]
name = "proc-macro-try-into-suggestion"
version = "0.0.0"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"

[dependencies]
derive = { path = "derive" }
